---
- hosts: all
  vars: 
    keyurl: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    repostring: "deb http://pkg.jenkins-ca.org/debian binary/"
  tasks: 
  - apt_key: url={{ keyurl }} state=present
  - apt_repository: repo="{{ repostring }}" state=present
  - apt: name={{ item }} state=latest
    with_items: 
    - build-essential
    - jenkins
    - libbz2-dev
    - libpcre3-dev
  - copy: src="files/lighttpd-1.4.37.tar.gz" dest="/var/lib/jenkins/lighttpd-1.4.37.tar.gz" owner=jenkins group=jenkins mode=0644
