---
- hosts: all
  vars: 
    keyurl: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
    repostring: "deb http://pkg.jenkins-ca.org/debian binary/"
  tasks: 
  - apt_key: url={{ keyurl }} state=present
  - apt_repository: repo="{{ repostring }}" state=present
  - apt: name=jenkins state=latest
